services:
  c2-js1:
    image: nats:2.10
    container_name: c2-js1 
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js1.conf:/etc/nats/nats.conf:ro
      - ./data/js1:/data
    ports:
      - "24222:4222"   # 客户端连接
      - "26222:6222"   # 集群内部通信
      - "27422:7422"   # 叶节点监听
      - "28222:8222"   # HTTP 监控
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

  c2-js2:
    image: nats:2.10
    container_name: c2-js2
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js2.conf:/etc/nats/nats.conf:ro
      - ./data/js2:/data
    ports:
      - "24223:4222"   # 客户端连接
      - "26223:6222"   # 集群内部通信
      - "27423:7422"   # 叶节点监听
      - "28223:8222"   # HTTP 监控
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

  c2-js3:
    image: nats:2.10
    container_name: c2-js3
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js3.conf:/etc/nats/nats.conf:ro
      - ./data/js3:/data
    ports:
      - "24224:4222"   # 客户端连接
      - "26224:6222"   # 集群内部通信
      - "27424:7422"   # 叶节点监听
      - "28224:8222"   # HTTP 监控
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

networks:
  default:
    name: nats-cluster