services:
  # --- Zone qa1a JetStream 节点 ---
  js1-qa1a:
    image: nats:2.10
    container_name: js1-qa1a 
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js1.conf:/etc/nats/nats.conf:ro
      - ./data/js1:/data
    ports:
      - "16222:4222"   # 客户端连接
      - "18222:8222"   # HTTP 监控
      - "17222:6222"   # 集群内部通信
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

  js2-qa1a:
    image: nats:2.10
    container_name: js2-qa1a
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js2.conf:/etc/nats/nats.conf:ro
      - ./data/js2:/data
    ports:
      - "16223:4222"
      - "18223:8222"
      - "17223:6222"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

  js3-qa1a:
    image: nats:2.10
    container_name: js3-qa1a
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./js3.conf:/etc/nats/nats.conf:ro
      - ./data/js3:/data
    ports:
      - "16224:4222"
      - "18224:8222"
      - "17224:6222"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"     # 单个日志文件最大 20MB
        max-file: "5"       # 最多保留 5 个文件（共 ~100MB）

  # --- Zone qa1a nats-box 服务 ---
  nats-box-qa1a:
    image: natsio/nats-box:latest
    container_name: nats-box-qa1a
    command: ["sh", "-c", "while true; do sleep 30; done"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nats", "--version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  default:
    name: dual-source-dual-mirror-network
    external: true

